### PR TITLE
RedStOnE liKe PowerThinGys

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
THIS sHouLd WaoUrK

### CODE REVIEW

**Comment by Gdeft** [comment]
oh no

**Comment by ThePythonGuy3** [comment]
WeLL YaS

**Comment by Gdeft** [comment]
What I meant by that is the range, since other power productions aren't flexible.

h

**Comment by ThePythonGuy3** [comment]
WdYmEan¿

**Comment by Gdeft** [comment]
lmao

**Comment by ThePythonGuy3** [comment]
LmAO¿

**Comment by Gdeft** [comment]
I'm going to close this ~~for now~~, I have a concept.

**Comment by ThePythonGuy3** [comment]
WeHavEDiSCoRd, WhyAReWeUsiNgThISPuLLAsAChaT

**Pull request closed without merging**
